version: '2'
services:
  app:
    retain_ip: true
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 5000
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 10000
      strategy: recreate
      reinitializing_timeout: 60000
  web:
    scale: 1
    start_on_create: true
    upgrade_strategy:
      start_first: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 8080
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 10000
      strategy: recreate
      request_line: 'GET "/" "HTTP/1.1\r\nHost: web.viewer-spin.dev-cattle.stable.spin.nersc.org"'
      reinitializing_timeout: 60000
